"""empty message

Revision ID: 36929bd315b9
Revises: 470262a26365
Create Date: 2020-12-30 06:33:14.591215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36929bd315b9'
down_revision = '470262a26365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'market_day', ['town_id'])
    op.drop_constraint('my_market_day_ibfk_1', 'my_market_day', type_='foreignkey')
    op.create_foreign_key(None, 'my_market_day', 'town', ['town_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'my_market_day', type_='foreignkey')
    op.create_foreign_key('my_market_day_ibfk_1', 'my_market_day', 'market_day', ['town_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'market_day', type_='unique')
    # ### end Alembic commands ###
