"""empty message

Revision ID: 470262a26365
Revises: 8958c7cfecb4
Create Date: 2020-12-30 06:17:38.952789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '470262a26365'
down_revision = '8958c7cfecb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # # op.create_table('my_market_day',
    # # sa.Column('created', sa.DateTime(), nullable=False),
    # # sa.Column('updated', sa.DateTime(), nullable=False),
    # # sa.Column('id', sa.Integer(), nullable=False),
    # # sa.Column('day', sa.DateTime(), nullable=False),
    # # sa.Column('town_id', sa.Integer(), nullable=False),
    # # sa.ForeignKeyConstraint(['town_id'], ['market_day.id'], ondelete='cascade'),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('id')
    # )
    # ### end Alembic commands ###
    pass

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'town', type_='unique')
    op.drop_constraint(None, 'region', type_='unique')
    op.drop_table('my_market_day')
    # ### end Alembic commands ###
