"""empty message

Revision ID: 8091bf5877c3
Revises: 
Create Date: 2020-12-29 11:48:12.111940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8091bf5877c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    )
    op.create_table('town',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    )
    op.create_table('market_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recent_day', sa.DateTime(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('town_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['town_id'], ['town.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_day')
    op.drop_table('town')
    op.drop_table('region')
    # ### end Alembic commands ###
